/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kiosko;

import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.plaf.metal.MetalBorders.ScrollPaneBorder;

/**
 *
 * @author 47321385n
 */
public class UserView extends javax.swing.JFrame {

    String[] book1 = {"libro 1 copy 1", "libro 1 copy 2", "libro 1 copy 3"};
    String[] book2 = {"libro 2 copy 1", "libro 2 copy 2", "libro 2 copy 3"};
    String[] book3 = {"libro 3 copy 1", "libro 3 copy 2", "libro 3 copy 3"};
    String[] book4 = {"libro 4 copy 1", "libro 4 copy 2", "libro 4 copy 3"};
    String[] book5 = {"libro 5 copy 1", "libro 5 copy 2", "libro 5 copy 3"};
    String[] book6 = {"libro 6 copy 1", "libro 6 copy 2", "libro 6 copy 3"};
    String[] book7 = {"libro 7 copy 1", "libro 7 copy 2", "libro 7 copy 3"};
    String[] book8 = {"libro 8 copy 1", "libro 8 copy 2", "libro 8 copy 3"};
    String[] book9 = {"libro 9 copy 1", "libro 9 copy 2", "libro 9 copy 3"};

    /**
     * Creates new form UserView2
     */
    public UserView() {
        initComponents();
        jList3.setVisible(false);
        this.setVisible(true);
        jLabel1.setText(homeMenu.getText());
    }

    public void listBooks(String[] a, DefaultListModel m) {
        jList3.setVisible(true);
        jScrollPane3.setBorder(new ScrollPaneBorder());
        for (int i = 0; i < a.length; i++) {
            m.add(i, a[i]);
        }
        jList3.setModel(m);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        homeMenu = new javax.swing.JMenuItem();
        resCopiesMenu = new javax.swing.JMenuItem();
        supportMenu = new javax.swing.JMenuItem();
        exitMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Libro 1", "Libro 2", "Libro 3", "Libro 4", "Libro 5", "Libro 6", "Libro 7", "Libro 8", "Libro 9" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane3.setBorder(null);

        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Copy 1", "Copy 2", "Copy 3", "Copy 4", "Copy 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList3.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList3ValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jList3);

        jLabel1.setText("jLabel1");

        jMenu1.setText("Menu");

        homeMenu.setText("Home");
        homeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeMenuActionPerformed(evt);
            }
        });
        jMenu1.add(homeMenu);

        resCopiesMenu.setText("Reserved copies");
        resCopiesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resCopiesMenuActionPerformed(evt);
            }
        });
        jMenu1.add(resCopiesMenu);

        supportMenu.setText("Support");
        supportMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supportMenuActionPerformed(evt);
            }
        });
        jMenu1.add(supportMenu);

        exitMenu.setText("Exit");
        exitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuActionPerformed(evt);
            }
        });
        jMenu1.add(exitMenu);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        String book = jList1.getSelectedValue();
        DefaultListModel m = new DefaultListModel();

        switch (book) {
            case "Libro 1":
                listBooks(book1, m);
                break;
            case "Libro 2":
                listBooks(book2, m);
                break;
            case "Libro 3":
                listBooks(book3, m);
                break;
            case "Libro 4":
                listBooks(book4, m);
                break;
            case "Libro 5":
                listBooks(book5, m);
                break;
            case "Libro 6":
                listBooks(book6, m);
                break;
            case "Libro 7":
                listBooks(book7, m);
                break;
            case "Libro 8":
                listBooks(book8, m);
                break;
            case "Libro 9":
                listBooks(book9, m);
                break;
        }

        if (!book.isEmpty()) {
            jList3.setVisible(true);
            jScrollPane3.setBorder(new ScrollPaneBorder());
        }


    }//GEN-LAST:event_jList1ValueChanged

    private void resCopiesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resCopiesMenuActionPerformed
        JFrame dos = new UserView2();
        dos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_resCopiesMenuActionPerformed

    private void jList3ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList3ValueChanged
        String book = jList3.getSelectedValue();
        int op = JOptionPane.showConfirmDialog(null, "Do you wanna reserv " + book + " ?");
        if (op == JOptionPane.CANCEL_OPTION) {
            jScrollPane3.setBorder(null);
            jList3.setVisible(false);
        }
    }//GEN-LAST:event_jList3ValueChanged

    private void homeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeMenuActionPerformed
        this.setVisible(false);
        JFrame home = new UserView();
        home.setVisible(true);
    }//GEN-LAST:event_homeMenuActionPerformed

    private void supportMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supportMenuActionPerformed
        this.setVisible(false);
        JFrame support = new UserView3();
        support.setVisible(true);
    }//GEN-LAST:event_supportMenuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jScrollPane3.setBorder(null);
        jList3.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void exitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuActionPerformed
        JOptionPane.showMessageDialog(null, "Bye", "", JOptionPane.INFORMATION_MESSAGE);
        JFrame login = new LoginView();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_exitMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem exitMenu;
    private javax.swing.JMenuItem homeMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JMenuItem resCopiesMenu;
    private javax.swing.JMenuItem supportMenu;
    // End of variables declaration//GEN-END:variables
}
